# Campus Twin AI — Model Training (YOLOv8n + LightGBM on BDG2)
Outputs (download these from the Output panel):
  models/best.pt          → person detector (webcam occupancy)
  models/forecast_B*.pkl  → per-building energy forecast
  models/metrics.json     → honest eval metrics
  data/elec_3b.csv        → cleaned 3-building hourly energy (simulator replay)

In [1]:
!pip -q install ultralytics lightgbm pyarrow
import torch, ultralytics
ultralytics.checks()
print("GPU:", torch.cuda.is_available(), torch.cuda.get_device_name(0) if torch.cuda.is_available() else "NONE")

Ultralytics 8.4.161 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Setup complete ✅ (4 CPUs, 31.3 GB RAM, 7037.7/8062.4 GB disk)
GPU: True Tesla T4

In [2]:
import glob, os
files = [p for p in glob.glob('/kaggle/input/**/*', recursive=True)
         if p.lower().endswith(('.parquet', '.csv'))]
print("Found files:")
for f in files: print(" ", f)

Found files:
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/water_cleaned.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/electricity_cleaned.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/steam_cleaned.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/water.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/gas.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/irrigation_cleaned.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/weather.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/hotwater_cleaned.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/irrigation.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/gas_cleaned.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/chilledwater.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/chilledwater_cleaned.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/hotwater.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/metadata.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/electricity.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/solar_cleaned.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/steam.csv
  /kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/solar.csv

In [5]:
import pandas as pd
import os

# Load electricity data
elec_path = "/kaggle/input/datasets/claytonmiller/buildingdatagenomeproject2/electricity_cleaned.csv"

df = pd.read_csv(elec_path)

print("Original shape:", df.shape)

# Convert timestamp
df["timestamp"] = pd.to_datetime(df["timestamp"])

# Set timestamp as index
df = df.set_index("timestamp")

print("After setting timestamp:", df.shape)

# Convert all building columns to numeric
df = df.apply(pd.to_numeric, errors="coerce")

# Find the 3 buildings with the most complete observations
best_cols = (
    df.notna()
      .sum()
      .sort_values(ascending=False)
      .head(3)
      .index
      .tolist()
)

print("\nSelected buildings:")
for i, col in enumerate(best_cols, 1):
    print(f"B{i}: {col}")

# Select those buildings
sub = df[best_cols].copy()

# Remove negative values
sub = sub.clip(lower=0)

# Resample to hourly data
sub = sub.resample("h").mean()

# Drop hours where any selected building is missing
sub = sub.dropna(how="any")

# Rename buildings
sub.columns = ["B1", "B2", "B3"]

sub.index.name = "timestamp"

# Create output directory
os.makedirs("/kaggle/working/data", exist_ok=True)

# Save cleaned dataset
output_path = "/kaggle/working/data/elec_3b.csv"
sub.to_csv(output_path)

print("\n" + "="*60)
print("FINAL DATASET")
print("="*60)
print("Shape:", sub.shape)
print("Saved to:", output_path)

print("\nData range:")
print("Start:", sub.index.min())
print("End:", sub.index.max())

print("\nMissing values:")
print(sub.isna().sum())

print("\nEnergy range:")
print("Minimum:", round(sub.min().min(), 3))
print("Maximum:", round(sub.max().max(), 3))

print("\nFirst 5 rows:")
display(sub.head())

Original shape: (17544, 1579)
After setting timestamp: (17544, 1578)

Selected buildings:
B1: Hog_office_Gustavo
B2: Lamb_office_Caitlin
B3: Lamb_health_Ken

============================================================
FINAL DATASET
============================================================
Shape: (17544, 3)
Saved to: /kaggle/working/data/elec_3b.csv

Data range:
Start: 2016-01-01 00:00:00
End: 2017-12-31 23:00:00

Missing values:
B1    0
B2    0
B3    0
dtype: int64

Energy range:
Minimum: 0.002
Maximum: 1205.446

First 5 rows:

                         B1    B2    B3
timestamp
2016-01-01 00:00:00  52.184   5.8   8.0
2016-01-01 01:00:00  52.184  11.3  14.9
2016-01-01 02:00:00  53.043  11.2  11.2
2016-01-01 03:00:00  52.801  11.9  11.4
2016-01-01 04:00:00  53.061  12.5  11.0

In [6]:
import lightgbm as lgb
import pickle
import json
import os
import time
import numpy as np
from sklearn.metrics import mean_absolute_error

os.makedirs("/kaggle/working/models", exist_ok=True)

FEATS = ['hour', 'dow', 'lag1', 'lag24', 'roll24']

metrics = {}

print("=" * 60)
print("LIGHTGBM TRAINING")
print("=" * 60)

total_start = time.time()

for b in ['B1', 'B2', 'B3']:

    start = time.time()

    print(f"\nTraining {b}...")

    s = sub[b]

    d = pd.DataFrame({'y': s})

    # Time features
    d['hour'] = d.index.hour
    d['dow'] = d.index.dayofweek

    # Lag features
    d['lag1'] = s.shift(1)
    d['lag24'] = s.shift(24)

    # Rolling 24-hour mean
    d['roll24'] = s.shift(1).rolling(24).mean()

    # Remove rows without enough history
    d = d.dropna()

    # Time-based split: 90% train, 10% test
    split = int(len(d) * 0.9)

    X = d[FEATS]
    y = d['y']

    X_train = X.iloc[:split]
    X_test = X.iloc[split:]

    y_train = y.iloc[:split]
    y_test = y.iloc[split:]

    print(f"Train samples: {len(X_train):,}")
    print(f"Test samples : {len(X_test):,}")

    # Model
    mdl = lgb.LGBMRegressor(
        n_estimators=300,
        learning_rate=0.05,
        num_leaves=31,
        random_state=42,
        verbosity=-1
    )

    mdl.fit(X_train, y_train)

    # Prediction
    pred = mdl.predict(X_test)

    # Metrics
    mae = mean_absolute_error(y_test, pred)

    # Avoid division by very small values
    denominator = y_test.clip(lower=1e-3)

    mape = (
        abs(y_test - pred) / denominator
    ).mean() * 100

    residuals = y_test - pred

    resid_std = residuals.std()

    metrics[b] = {
        'mae_kwh': round(float(mae), 3),
        'mape_pct': round(float(mape), 2),
        'resid_std': round(float(resid_std), 3)
    }

    # Save model
    model_path = f"/kaggle/working/models/forecast_{b}.pkl"

    with open(model_path, 'wb') as f:
        pickle.dump(mdl, f)

    elapsed = time.time() - start

    print(f"MAE       : {mae:.3f}")
    print(f"MAPE      : {mape:.2f}%")
    print(f"Residual σ: {resid_std:.3f}")
    print(f"Saved     : {model_path}")
    print(f"Time      : {elapsed:.2f} sec")

# Save metrics
metrics_path = "/kaggle/working/models/metrics.json"

with open(metrics_path, 'w') as f:
    json.dump(metrics, f, indent=2)

total_time = time.time() - total_start

print("\n" + "=" * 60)
print("TRAINING COMPLETE")
print("=" * 60)

print(f"Total training time: {total_time:.2f} seconds")

print("\nMetrics:")
print(json.dumps(metrics, indent=2))

print("\nSaved files:")
print(" - forecast_B1.pkl")
print(" - forecast_B2.pkl")
print(" - forecast_B3.pkl")
print(" - metrics.json")

============================================================
LIGHTGBM TRAINING
============================================================

Training B1...
Train samples: 15,768
Test samples : 1,752
MAE       : 12.091
MAPE      : 1.66%
Residual σ: 23.329
Saved     : /kaggle/working/models/forecast_B1.pkl
Time      : 0.44 sec

Training B2...
Train samples: 15,768
Test samples : 1,752
MAE       : 5.528
MAPE      : 13.80%
Residual σ: 9.215
Saved     : /kaggle/working/models/forecast_B2.pkl
Time      : 0.34 sec

Training B3...
Train samples: 15,768
Test samples : 1,752
MAE       : 1.910
MAPE      : 9.72%
Residual σ: 2.688
Saved     : /kaggle/working/models/forecast_B3.pkl
Time      : 0.34 sec

============================================================
TRAINING COMPLETE
============================================================
Total training time: 1.12 seconds

Metrics:
{
  "B1": {
    "mae_kwh": 12.091,
    "mape_pct": 1.66,
    "resid_std": 23.329
  },
  "B2": {
    "mae_kwh": 5.528,
    "mape_pct": 13.8,
    "resid_std": 9.215
  },
  "B3": {
    "mae_kwh": 1.91,
    "mape_pct": 9.72,
    "resid_std": 2.688
  }
}

Saved files:
 - forecast_B1.pkl
 - forecast_B2.pkl
 - forecast_B3.pkl
 - metrics.json

In [7]:
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

print("YOLO model loaded successfully")

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8n.pt to 'yolov8n.pt': 100% ━━━━━━━━━━━━ 6.2MB 104.1MB/s 0.1s
YOLO model loaded successfully

In [8]:
results = model.train(
    data="coco128.yaml",
    classes=[0],
    epochs=40,
    imgsz=640,
    batch=32,
    device=0,
    project="/kaggle/working/yolo",
    name="person"
)

Ultralytics 8.4.161 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=[0], close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco128.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=40, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=person, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/kaggle/working/yolo, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/yolo/person, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None

WARNING ⚠️ Dataset 'coco128.yaml' images not found, missing path '/kaggle/working/datasets/coco128/images/train2017'
Downloading https://ultralytics.com/assets/coco128.zip to '/kaggle/working/datasets/coco128.zip': 100% ━━━━━━━━━━━━ 6.7MB 95.1MB/s 0.1s
Unzipping /kaggle/working/datasets/coco128.zip to /kaggle/working/datasets/coco128...: 100% ━━━━━━━━━━━━ 263/263 2.9Kfiles/s 0.1s
Dataset download success ✅ (0.4s), saved to /kaggle/working/datasets

Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 22.4MB/s 0.0s

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.head.Detect           [80, 16, None, [64, 128, 256]]
Model summary: 129 layers, 3,157,200 parameters, 3,157,184 gradients, 8.9 GFLOPs

Transferred 355/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: downloading yolo26n.pt for AMP checks (one-time, not used for training)...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'weights/yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 97.9MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 961.1±436.3 MB/s, size: 46.0 KB)
train: Scanning /kaggle/working/datasets/coco128/labels/train2017... 126 images, 2 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 128/128 1.1Kit/s 0.1s<0.1s
train: New cache created: /kaggle/working/datasets/coco128/labels/train2017.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1578.6±674.8 MB/s, size: 56.4 KB)
val: Scanning /kaggle/working/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 128/128 41.3Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to /kaggle/working/yolo/person/labels.jpg...
Using 128 train, 128 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /kaggle/working/yolo/person
Starting training for 40 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/40      4.39G      1.138      2.172       1.21        146        640: 100% ━━━━━━━━━━━━ 4/4 1.1s/it 4.2s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.2it/s 1.6s4.3s
                   all        128        254      0.799      0.657      0.755      0.533

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/40      6.02G      1.279        2.2      1.199        130        640: 0% ──────────── 0/4  0.2s

/usr/local/lib/python3.12/dist-packages/ray/train/_internal/session.py:676: UserWarning: `get_trial_id` is meant to only be called inside a function that is executed by a Tuner or Trainer. Returning `None`.
  warnings.warn(

       2/40      6.02G      1.085      2.038       1.19         99        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.9it/s 0.7s1.1s
                   all        128        254      0.822      0.669      0.759      0.539

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/40      6.02G      1.133       1.26      1.161        120        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s0.9s
                   all        128        254       0.83      0.651      0.767      0.546

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/40      6.02G      1.198      1.024      1.157        132        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.0s
                   all        128        254      0.836      0.685      0.776      0.558

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/40      6.02G      1.131     0.9204      1.192        122        640: 100% ━━━━━━━━━━━━ 4/4 5.3it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.7s1.0s
                   all        128        254      0.813      0.709      0.785      0.565

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/40      6.02G      1.098     0.8731      1.122        158        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.7s1.0s
                   all        128        254      0.822      0.713      0.788      0.573

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/40      6.02G      1.107     0.9353       1.17        147        640: 100% ━━━━━━━━━━━━ 4/4 5.3it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.0s
                   all        128        254      0.809      0.681      0.784       0.57

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/40      6.02G      1.133     0.8703      1.125         87        640: 100% ━━━━━━━━━━━━ 4/4 5.3it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.0s
                   all        128        254      0.845      0.666      0.784      0.566

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/40      6.02G      1.074     0.8255      1.133         73        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s0.8s
                   all        128        254      0.841      0.689       0.79      0.565

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/40      6.02G      0.971     0.7716      1.067        102        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s0.9s
                   all        128        254      0.832      0.709      0.806      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/40      6.02G      1.041      0.832       1.09        126        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s1.0s
                   all        128        254      0.847       0.72      0.816      0.601

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/40      6.02G      1.016     0.8101      1.117        128        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s1.1s
                   all        128        254      0.873      0.705      0.823      0.614

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/40      6.02G      1.055     0.7829      1.099        101        640: 100% ━━━━━━━━━━━━ 4/4 5.3it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.9it/s 0.7s1.0s
                   all        128        254      0.883      0.714      0.832      0.619

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/40      6.02G     0.9414     0.6923      1.071        110        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s0.9s
                   all        128        254      0.909      0.689      0.833       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/40      6.02G      0.992     0.7615      1.092        119        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s0.9s
                   all        128        254      0.944      0.654      0.836      0.626

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/40      6.02G     0.9163     0.7123      1.068        112        640: 100% ━━━━━━━━━━━━ 4/4 5.3it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.0s
                   all        128        254      0.955      0.668      0.842       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/40      6.02G      0.905     0.6837      1.048        106        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.1s
                   all        128        254      0.952      0.673      0.846      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/40      6.02G     0.9584     0.6981      1.046        100        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s1.0s
                   all        128        254      0.857      0.734       0.85      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/40      6.02G      0.955     0.7191      1.106         84        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s1.0s
                   all        128        254       0.85       0.76      0.853      0.647

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/40      6.02G     0.9621     0.7327      1.048         91        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.0s
                   all        128        254      0.862      0.762      0.857      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/40      6.02G     0.9634     0.6942      1.057        157        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s0.9s
                   all        128        254      0.878      0.764      0.865      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/40      6.02G     0.9425     0.6771      1.043         99        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s0.9s
                   all        128        254      0.892       0.76      0.867      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/40      6.02G     0.9286     0.6844       1.04        109        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s1.0s
                   all        128        254      0.925       0.76      0.869      0.661

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/40      6.02G     0.9899     0.7587      1.104        122        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s1.0s
                   all        128        254      0.926      0.752      0.871      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/40      6.02G     0.9533     0.6623      1.073         93        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s0.9s
                   all        128        254      0.928      0.748      0.873      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/40      6.02G      0.919     0.6696      1.069         96        640: 100% ━━━━━━━━━━━━ 4/4 5.3it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.0s
                   all        128        254      0.928      0.758       0.88      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/40      6.02G       0.89     0.6704      1.081         87        640: 100% ━━━━━━━━━━━━ 4/4 5.3it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s1.1s
                   all        128        254      0.928      0.757      0.877      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/40      6.02G     0.8988     0.6835      1.056        119        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.0s
                   all        128        254      0.928      0.762      0.883      0.684

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/40      6.02G      0.973     0.6535      1.066        159        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s0.9s
                   all        128        254      0.904      0.782       0.88       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/40      6.02G      0.781      0.585      1.001         82        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s1.0s
                   all        128        254      0.905      0.791      0.883      0.693
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/40      6.02G     0.8486     0.7044     0.9742         45        640: 100% ━━━━━━━━━━━━ 4/4 2.0it/s 2.0s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.7it/s 0.7s1.0s
                   all        128        254      0.913      0.787      0.887      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/40      6.02G     0.9037     0.6951      1.023         58        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s1.0s
                   all        128        254      0.913      0.789      0.889      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/40      6.02G     0.9884     0.7072      1.044         50        640: 100% ━━━━━━━━━━━━ 4/4 5.3it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s1.1s
                   all        128        254      0.928      0.783      0.888      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      34/40      6.02G      0.903     0.6466      1.008         46        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s1.0s
                   all        128        254      0.925      0.776      0.885       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      35/40      6.02G     0.8778     0.6055      1.018         88        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.0it/s 0.5s0.7s
                   all        128        254       0.93      0.784      0.885      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      36/40      6.02G     0.8481     0.6034     0.9807         82        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.5it/s 0.6s0.9s
                   all        128        254      0.929      0.776      0.884      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      37/40      6.02G     0.8426     0.6468     0.9526         59        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s0.8s
                   all        128        254      0.934      0.776      0.884      0.684

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      38/40      6.02G     0.8474     0.5851     0.9845         69        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s0.8s
                   all        128        254      0.934      0.775      0.884      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      39/40      6.02G     0.8376     0.6318      1.018         42        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s0.8s
                   all        128        254      0.929      0.777      0.886      0.684

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      40/40      6.02G     0.8867     0.6731      1.019         54        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s1.0s
                   all        128        254      0.929      0.776      0.884      0.683

40 epochs completed in 0.021 hours.
Optimizer stripped from /kaggle/working/yolo/person/weights/last.pt, 6.5MB
Optimizer stripped from /kaggle/working/yolo/person/weights/best.pt, 6.5MB

Validating /kaggle/working/yolo/person/weights/best.pt...
Ultralytics 8.4.161 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 72 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.4it/s 1.4s1.4s
                   all        128        254      0.908      0.791      0.884      0.691
                person         61        254      0.908      0.791      0.884      0.691
Speed: 1.1ms preprocess, 4.5ms inference, 0.0ms loss, 1.6ms postprocess per image
Results saved to /kaggle/working/yolo/person

In [9]:
#hyparameter tunning 
from ultralytics import YOLO
import pandas as pd, time, os, shutil

experiments = [
    ("baseline", 0.01, "SGD",   640, 32, 40),
    ("low_lr",   0.005, "SGD",  640, 32, 60),
    ("adamw",    0.001, "AdamW",640, 32, 60),
    ("high_res", 0.005, "AdamW",768, 16, 60),
]

results = []
out = "/kaggle/working/yolo_tuning"

for name, lr, opt, imgsz, batch, epochs in experiments:
    print(f"\n========== {name} ==========")
    t = time.time()

    model = YOLO("yolov8n.pt")
    model.train(
        data="coco128.yaml",
        classes=[0],
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
        optimizer=opt,
        lr0=lr,
        weight_decay=0.0005,
        device=0,
        seed=42,
        project=out,
        name=name,
        exist_ok=True,
        verbose=False
    )

    path = f"{out}/{name}/weights/best.pt"
    m = YOLO(path).val(
        data="coco128.yaml",
        classes=[0],
        imgsz=imgsz,
        batch=batch,
        device=0,
        verbose=False
    )

    results.append({
        "experiment": name,
        "optimizer": opt,
        "lr": lr,
        "imgsz": imgsz,
        "batch": batch,
        "epochs": epochs,
        "precision": round(float(m.box.mp), 4),
        "recall": round(float(m.box.mr), 4),
        "mAP50": round(float(m.box.map50), 4),
        "mAP50-95": round(float(m.box.map), 4),
        "time_sec": round(time.time()-t, 1),
        "model": path
    })

df = pd.DataFrame(results).sort_values("mAP50-95", ascending=False)

display(df)

# Save results
df.to_csv("/kaggle/working/yolo_tuning_results.csv", index=False)

# Copy best model
best_path = df.iloc[0]["model"]
os.makedirs("/kaggle/working/models", exist_ok=True)
shutil.copy(best_path, "/kaggle/working/models/best_tuned.pt")

print("\nBEST MODEL:")
print(df.iloc[0])
print("\nSaved: /kaggle/working/models/best_tuned.pt")

========== baseline ==========
Ultralytics 8.4.161 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=[0], close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco128.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=40, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=baseline, nbs=64, nms=None, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/kaggle/working/yolo_tuning, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/yolo_tuning/baseline, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.head.Detect           [80, 16, None, [64, 128, 256]]
Model summary: 129 layers, 3,157,200 parameters, 3,157,184 gradients, 8.9 GFLOPs

Transferred 355/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1220.8±417.4 MB/s, size: 41.3 KB)
train: Scanning /kaggle/working/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 128/128 48.8Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1378.2±571.6 MB/s, size: 81.0 KB)
val: Scanning /kaggle/working/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 128/128 53.7Mit/s 0.0s
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to /kaggle/working/yolo_tuning/baseline/labels.jpg...
Using 128 train, 128 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /kaggle/working/yolo_tuning/baseline
Starting training for 40 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/40       4.4G      1.255      1.912      1.191        110        640: 100% ━━━━━━━━━━━━ 4/4 1.5it/s 2.6s0.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 1.2s/it 2.3s6.7s
                   all        128        254      0.812      0.648      0.754      0.534

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/40      6.02G      1.262       1.91      1.261        109        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s1.1s
                   all        128        254      0.821       0.65      0.755      0.536

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/40      6.02G      1.258      1.377      1.219        174        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.8it/s 0.7s1.0s
                   all        128        254      0.772      0.602      0.702      0.478

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/40      6.02G      1.156       1.22      1.183        130        640: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.1s
                   all        128        254      0.768      0.599      0.705      0.482

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/40      6.02G      1.183      1.273      1.116        105        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s1.1s
                   all        128        254      0.544      0.575      0.557      0.293

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/40      6.02G      1.147      1.434      1.129        111        640: 100% ━━━━━━━━━━━━ 4/4 4.9it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s1.1s
                   all        128        254      0.483      0.566      0.545      0.357

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/40      6.02G      1.171      1.181      1.144        117        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s0.9s
                   all        128        254      0.729      0.555      0.637      0.414

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/40      6.02G      1.081      1.087      1.125        111        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s0.9s
                   all        128        254       0.69      0.547      0.616      0.387

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/40      6.02G      1.233      1.096      1.214        121        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s1.1s
                   all        128        254      0.722      0.512       0.63      0.412

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/40      6.02G      1.166     0.9403      1.144        110        640: 100% ━━━━━━━━━━━━ 4/4 4.9it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.1s
                   all        128        254      0.652      0.567      0.632      0.383

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/40      6.02G      1.231       1.09      1.236         82        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s1.1s
                   all        128        254      0.667      0.543      0.604      0.378

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/40      6.02G      1.174     0.9542      1.138        120        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s1.1s
                   all        128        254       0.71      0.491      0.557      0.364

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/40      6.02G      1.165     0.9125      1.106        143        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.1s
                   all        128        254      0.715      0.503      0.578      0.367

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/40      6.02G      1.215     0.9901      1.143        109        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.1s
                   all        128        254      0.745      0.535       0.63      0.403

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/40      6.02G      1.135     0.9682      1.168        113        640: 100% ━━━━━━━━━━━━ 4/4 4.9it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s1.0s
                   all        128        254      0.712      0.516      0.597      0.373

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/40      6.02G      1.101     0.9469      1.107        105        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s1.0s
                   all        128        254      0.769      0.523      0.612      0.363

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/40      6.02G      1.122     0.9357      1.124        133        640: 100% ━━━━━━━━━━━━ 4/4 4.9it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s1.2s
                   all        128        254      0.719      0.544      0.614      0.373

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/40      6.02G       1.11     0.9073      1.136        153        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s1.1s
                   all        128        254      0.694      0.563      0.653      0.382

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/40      6.02G      1.177      1.002      1.108        146        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.1s
                   all        128        254      0.689      0.555      0.606      0.333

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/40      6.02G      1.053     0.9423      1.123        119        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s1.0s
                   all        128        254      0.655      0.583      0.628       0.34

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/40      6.02G      1.102     0.9361      1.153        105        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s1.1s
                   all        128        254      0.725      0.543      0.621      0.345

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/40      6.02G     0.9944     0.8755        1.1        127        640: 100% ━━━━━━━━━━━━ 4/4 4.9it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s1.0s
                   all        128        254      0.726      0.564      0.633      0.376

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/40      6.02G      1.117     0.8769      1.098        113        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s1.1s
                   all        128        254      0.704      0.587      0.635       0.38

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/40      6.02G      1.067     0.8557      1.137        177        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s1.0s
                   all        128        254      0.756      0.638      0.701      0.471

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/40      6.02G      1.009     0.8408      1.099        114        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.4it/s 0.6s1.0s
                   all        128        254      0.737      0.728      0.777      0.522

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/40      6.02G     0.9864     0.7688      1.074         78        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s1.0s
                   all        128        254      0.863      0.638      0.775      0.527

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/40      6.02G      1.004      0.772      1.076        138        640: 100% ━━━━━━━━━━━━ 4/4 4.9it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s1.0s
                   all        128        254      0.862      0.736      0.838      0.577

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/40      6.02G     0.9949     0.7708      1.057        159        640: 100% ━━━━━━━━━━━━ 4/4 4.9it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s0.9s
                   all        128        254      0.897      0.683      0.821      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/40      6.02G      1.018     0.7839      1.075        148        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s1.1s
                   all        128        254      0.838      0.744      0.833      0.602

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/40      6.02G      1.037      0.771      1.086        152        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.0s
                   all        128        254      0.858       0.74      0.846      0.613
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/40      6.02G     0.9606     0.8252      1.054         63        640: 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.3s0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.8it/s 0.7s1.2s
                   all        128        254      0.865      0.744      0.844      0.621

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/40      6.02G     0.9219     0.7306      1.033         42        640: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s1.0s
                   all        128        254      0.845      0.749      0.843      0.617

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/40      6.02G     0.9102      0.716      1.026         44        640: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.1it/s 0.6s1.0s
                   all        128        254       0.86      0.764      0.851       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      34/40      6.02G      0.906     0.6672      1.021         54        640: 100% ━━━━━━━━━━━━ 4/4 4.9it/s 0.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s1.0s
                   all        128        254      0.861      0.756      0.851      0.631

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

,experiment,optimizer,lr,imgsz,batch,epochs,precision,recall,mAP50,mAP50-95,time_sec,model
1,low_lr,SGD,0.005,640,32,60,0.9698,0.8425,0.9197,0.7428,121.1,/kaggle/working/yolo_tuning/low_lr/weights/bes...
2,adamw,AdamW,0.001,640,32,60,0.9238,0.8504,0.9120,0.7266,128.3,/kaggle/working/yolo_tuning/adamw/weights/best.pt
0,baseline,SGD,0.010,640,32,40,0.9124,0.8031,0.8928,0.6906,88.5,/kaggle/working/yolo_tuning/baseline/weights/b...
3,high_res,AdamW,0.005,768,16,60,0.4842,0.3918,0.3593,0.1419,162.0,/kaggle/working/yolo_tuning/high_res/weights/b...

BEST MODEL:
experiment                                               low_lr
optimizer                                                   SGD
lr                                                        0.005
imgsz                                                       640
batch                                                        32
epochs                                                       60
precision                                                0.9698
recall                                                   0.8425
mAP50                                                    0.9197
mAP50-95                                                 0.7428
time_sec                                                  121.1
model         /kaggle/working/yolo_tuning/low_lr/weights/bes...
Name: 1, dtype: object

Saved: /kaggle/working/models/best_tuned.pt

In [10]:
model = YOLO(
    "/kaggle/working/yolo/person/weights/best.pt"
)

metrics_yolo = model.val()

print(metrics_yolo)

Ultralytics 8.4.161 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
Model summary (fused): 72 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1656.0±465.1 MB/s, size: 59.4 KB)
val: Scanning /kaggle/working/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 128/128 28.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.7it/s 2.2s0.2s
                   all        128        929      0.245      0.104      0.097       0.06
                person         61        254     0.0754      0.953      0.885      0.689
               bicycle          3          6          0          0          0          0
                   car         12         46       0.75     0.0652     0.0488       0.02
            motorcycle          4          5          0          0          0          0
              airplane          5          6          1      0.167      0.165      0.099
                   bus          5          7          1      0.286      0.285      0.257
                 train          3          3          1      0.667      0.665        0.4
                 truck          5         12      0.167     0.0833     0.0142    0.00425
                  boat          2          6          0          0          0          0
         traffic light          4         14          0          0          0          0
             stop sign          2          2          0          0          0          0
                 bench          5          9          0          0          0          0
                  bird          2         16          1       0.25      0.245      0.148
                   cat          4          4          1       0.25      0.245      0.171
                   dog          9          9          1      0.111      0.115      0.103
                 horse          1          2          0          0          0          0
              elephant          4         17          1     0.0588      0.055      0.055
                  bear          1          1          0          0          0          0
                 zebra          2          4          1          1      0.995      0.957
               giraffe          4          9          0          0          0          0
              backpack          4          6      0.333      0.167      0.165     0.0935
              umbrella          4         18      0.389      0.389      0.315      0.159
               handbag          9         19          0          0          0          0
                   tie          6          7          1      0.143      0.145     0.0145
              suitcase          2          4          0          0          0          0
               frisbee          5          5          0          0          0          0
                  skis          1          1          1          1      0.995      0.199
             snowboard          2          7          0          0          0          0
           sports ball          6          6          1      0.167      0.165     0.0825
                  kite          2         10      0.333        0.1     0.0475     0.0095
          baseball bat          4          4          0          0          0          0
        baseball glove          4          7          0          0          0          0
            skateboard          3          5          0          0          0          0
         tennis racket          5          7          1      0.143      0.145      0.116
                bottle          6         18        0.2     0.0556      0.055      0.044
            wine glass          5         16          0          0          0          0
                   cup         10         36          0          0          0          0
                  fork          6          6          0          0          0          0
                 knife          7         16          0          0          0          0
                 spoon          5         22          0          0          0          0
                  bowl          9         28          0          0          0          0
                banana          1          1          0          0          0          0
              sandwich          2          2          0          0          0          0
                orange          1          4          0          0          0          0
              broccoli          4         11          0          0          0          0
                carrot          3         24          0          0          0          0
               hot dog          1          2          0          0          0          0
                 pizza          5          5          0          0          0          0
                 donut          2         14          0          0          0          0
                  cake          4          4          0          0          0          0
                 chair          9         35      0.273     0.0857      0.055     0.0265
                 couch          5          6      0.625      0.833      0.835      0.478
          potted plant          9         14          1     0.0714      0.075      0.045
                   bed          3          3          0          0          0          0
          dining table         10         13      0.214      0.231     0.0775     0.0573
                toilet          2          2          0          0          0          0
                    tv          2          2          0          0          0          0
                laptop          2          3          0          0          0          0
                 mouse          2          2          0          0          0          0
                remote          5          8          0          0          0          0
            cell phone          5          8          0          0          0          0
             microwave          3          3          0          0          0          0
                  oven          5          5          0          0          0          0
                  sink          4          6          0          0          0          0
          refrigerator          5          5          0          0          0          0
                  book          6         29          0          0          0          0
                 clock          8          9          0          0          0          0
                  vase          2          2          0          0          0          0
              scissors          1          1          0          0          0          0
            teddy bear          6         21          1     0.0952      0.095      0.033
            toothbrush          2          5          0          0          0          0
Speed: 2.4ms preprocess, 6.5ms inference, 0.0ms loss, 2.9ms postprocess per image
Results saved to /kaggle/working/runs/detect/val-5
ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 38, 39, 40, 41, 42, 43, 44, 45, 46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 67, 68, 69, 71, 72, 73, 74, 75, 76, 77, 79])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7e6c9478e750>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,

In [11]:
import os
import json
import joblib

print("=== Forecast Models ===")

for b in ["B1", "B2", "B3"]:
    path = f"/kaggle/working/models/forecast_{b}.pkl"
    print(b, "✓" if os.path.exists(path) else "✗", path)

metrics_path = "/kaggle/working/models/metrics.json"

if os.path.exists(metrics_path):
    with open(metrics_path) as f:
        metrics = json.load(f)

    print("\n=== Metrics ===")
    print(json.dumps(metrics, indent=2))

=== Forecast Models ===
B1 ✓ /kaggle/working/models/forecast_B1.pkl
B2 ✓ /kaggle/working/models/forecast_B2.pkl
B3 ✓ /kaggle/working/models/forecast_B3.pkl

=== Metrics ===
{
  "B1": {
    "mae_kwh": 12.091,
    "mape_pct": 1.66,
    "resid_std": 23.329
  },
  "B2": {
    "mae_kwh": 5.528,
    "mape_pct": 13.8,
    "resid_std": 9.215
  },
  "B3": {
    "mae_kwh": 1.91,
    "mape_pct": 9.72,
    "resid_std": 2.688
  }
}

In [12]:
import os
import shutil

os.makedirs("/kaggle/working/models", exist_ok=True)

baseline = "/kaggle/working/yolo_tuning/baseline/weights/best.pt"

if os.path.exists(baseline):
    shutil.copy(
        baseline,
        "/kaggle/working/models/best.pt"
    )
    print("Saved:", "/kaggle/working/models/best.pt")
else:
    print("Baseline model not found")

Saved: /kaggle/working/models/best.pt

In [13]:
import shutil
import os

model_dir = "/kaggle/working/models"

zip_path = shutil.make_archive(
    "/kaggle/working/campus_twin_models",
    "zip",
    model_dir
)

print("Created:")
print(zip_path)

Created:
/kaggle/working/campus_twin_models.zip